galaxy_systemd_mode: "zerg" # alternatively "mule"

# Mule Options
galaxy_systemd_memory_limit_mule: 32

# Zergling Options
galaxy_systemd_zerglings: 2
galaxy_systemd_handlers: 12
galaxy_systemd_workflow_schedulers: 0

# In GB
galaxy_systemd_memory_limit: 16
galaxy_systemd_memory_limit_reports: 5
galaxy_systemd_memory_limit_handler: 5
galaxy_systemd_memory_limit_workflow: 5
galaxy_systemd_memory_limit_zp: 8
galaxy_zergpool: true
galaxy_zergpool_listen_addr: "127.0.0.1:4001"
galaxy_zergpool_socket_name: zergpool.sock
galaxy_zergpool_listen_path: "{{ galaxy_mutable_data_dir }}/{{ galaxy_zergpool_socket_name }}"

galaxy_systemd_zergling_env: ""
galaxy_systemd_handler_env: ""

galaxy_systemd_reports: false
galaxy_reports_path: "{{ galaxy_config_dir  }}/reports.yml"
