- hosts: immunohub_server
  become: true
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['git', 'make', 'python3-psycopg2', 'python3-virtualenv.noarch', 'bzip2', 'gcc', 'python3-lxml']
    - name: Print ansible_os_family
      debug: var=ansible_os_family
         
  # systemd      
  handlers:
    - name: Restart Galaxy
      systemd:
        name: galaxy
        state: restarted
        
  roles:
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - geerlingguy.pip
    - galaxyproject.galaxy
      become: true
    - nginx.rhel
      become: true
    - selinux.galaxy
    - usegalaxy_eu.galaxy_systemd

  post_tasks:
      
   # Check if database dir exists
    - name: Check if directory database exists
      stat: path="/srv/galaxy-dev/server/database/"
      register: database_dir

   # Rename database dir to unused
    - name: Move database to database_unused
      command: mv /srv/galaxy-dev/server/database  /srv/galaxy-dev/server/database_unused/
      when: database_dir.stat.exists

    # Create a link database pointing to /storage/galaxy_data instead of using database directory
    - name: Create a link database
      file:
             src: /storage/galaxy_dev_data/
             dest:  /srv/galaxy_dev/server/database
             owner: galaxy
             group: galaxy
             state: link
      
