---
galaxy_info:
  author: Galaxy Europe
  description: Manage a Galaxy server with systemd.
  company: Galaxy Europe
  license: GPL-3.0
  min_ansible_version: 2.5
  role_name: galaxy-systemd
  platforms:
  - name: EL
    versions:
    - all
  - name: GenericUNIX
    versions:
    - all
    - any
  - name: Fedora
    versions:
    - all
  - name: opensuse
    versions:
    - all
  - name: Amazon
    versions:
    - all
  - name: GenericBSD
    versions:
    - all
    - any
  - name: FreeBSD
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: SLES
    versions:
    - all
  - name: GenericLinux
    versions:
    - all
    - any
  - name: Debian
    versions:
    - all
  galaxy_tags:
  - system
  - web
dependencies: []
allow_duplicates: yes
