---

- name: Install Nginx in RHEL
  yum:
    pkg: nginx
  notify:
    - start nginx
        
- name: Copy nginx conf files
  copy: 
       src: "{{ nginx_conf_files_src_dir}}/"
       dest: "{{ nginx_custom_conf_files_dir }}"
  
# Restart nginx
- name: Restart nginx
  service: name=nginx state=restarted
