- name: Deploy Galaxy Reports unit
  template:
    owner: root
    group: root
    mode: 0644
    src: galaxy-reports.service.j2
    dest: /etc/systemd/system/galaxy-reports.service
  notify: galaxy handler daemon reload

- name: Enable reports and ensure it is running
  systemd:
    name: galaxy-reports.service
    enabled: yes
    state: started
