---
# Manage Galaxy framework dependencies

- name: Manage dependencies
  block:

    - name: Include virtualenv setup tasks
      import_tasks: virtualenv.yml

    # virtualenv_command is still required if `virtualenv` isn't on $PATH, even if the venv already exists.
    - name: Install Galaxy base dependencies
      pip:
        requirements: "{{ galaxy_requirements_file }}"
        extra_args: "--index-url https://wheels.galaxyproject.org/simple/ --extra-index-url https://pypi.python.org/simple {{ pip_extra_args | default('') }}"
        virtualenv: "{{ galaxy_venv_dir }}"
        virtualenv_command: "{{ galaxy_virtualenv_command | default(pip_virtualenv_command | default(omit)) }}"
      environment:
        PYTHONPATH: null
        VIRTUAL_ENV: "{{ galaxy_venv_dir }}"

    - name: Collect Galaxy conditional dependency requirement strings
      command: "{{ galaxy_venv_dir }}/bin/python -c \"import galaxy.dependencies; print('\\n'.join(galaxy.dependencies.optional('{{ galaxy_config_file }}')))\""
      environment:
        PYTHONPATH: "{{ galaxy_server_dir }}/lib"
      register: conditional_dependencies
      changed_when: no

    - name: Install Galaxy conditional dependencies
      pip:
        name: "{{ conditional_dependencies.stdout_lines }}"
        extra_args: "--index-url https://wheels.galaxyproject.org/simple/ --extra-index-url https://pypi.python.org/simple {{ pip_extra_args | default('') }}"
        virtualenv: "{{ galaxy_venv_dir }}"
        virtualenv_command: "{{ galaxy_virtualenv_command | default(pip_virtualenv_command | default(omit)) }}"
      environment:
        PYTHONPATH: null
        VIRTUAL_ENV: "{{ galaxy_venv_dir }}"
      when: (not ansible_check_mode) and conditional_dependencies.stdout_lines | length > 0
      
      # Nikolay 
    - name: Set ownership of all dirs to galaxy 
      file:
        path: "{{ item }}"
        owner: "{{ __galaxy_user_name }}"
        group: "{{ __galaxy_user_group }}"
        mode: "{{ __galaxy_dir_perms }}"
      with_items: "{{ galaxy_venv_dir }}"

  #remote_user: "{{ galaxy_remote_users.privsep | default(omit) }}"
  #become: "{{ true if galaxy_become_users.privsep is defined else __galaxy_become }}"
  #become_user: "{{ galaxy_become_users.privsep | default(ansible_user_id) }}"
  
  remote_user: "{{ galaxy_remote_users.galaxy | default(omit) }}"
  become: "{{ true if galaxy_become_users.galaxy is defined else __galaxy_become }}"
  become_user: "{{ galaxy_become_users.galaxy | default(ansible_user_id) }}"
  
