---
# main tasks file for galaxyproject.galaxy

# Deploy a Galaxy server
#   https://docs.galaxyproject.org/

- fail:
    msg: "Variables galaxy_manage_clone and galaxy_manage_download cannot both be true."
  when: galaxy_manage_clone and galaxy_manage_download

# To my knowledge there is no other way to know whether or not the consumer of this role has set `become: true` outside
# this role, and `become: {{ foo | default(omit) }}` on a task/block actually clobbers the higher level use of `become`.
# This is a temporary solution.
- name: Determine if become is in use
  set_fact:
    __galaxy_become: "{{ ansible_env.SUDO_USER is defined }}"

- name: Import layout variable tasks
  import_tasks: layout.yml
  tags: always

# Nikolay USIT - comment, RHEL8 cfengine does not allow editing of /etc/passw

#- name: Include user creation tasks
  #include_tasks: user.yml
  #when: galaxy_create_user or galaxy_create_privsep_user
  #tags:
    #- galaxy_create_user

- name: Include path management tasks
  include_tasks: paths.yml
  when: galaxy_manage_paths
  tags:
    - galaxy_manage_paths

- name: Include clone tasks
  include_tasks: clone.yml
  when: galaxy_manage_clone
  tags: galaxy_manage_clone

- name: Include download tasks
  include_tasks: download.yml
  when: galaxy_manage_download
  tags: galaxy_manage_download

- name: Include static config setup tasks
  include_tasks: static_setup.yml
  when: galaxy_manage_static_setup
  tags: galaxy_config_files
  
  # Nikolay 
- name: Include start-page tasks and adding customized immuno welcome page
  include_tasks: start-page.yml
  when: galaxy_manage_static_setup
  tags: galaxy_default_start_welcome
  
  # Nikolay 
- name: Include immunohub-configuration tasks
  include_tasks: immunohub-configuration.yml
  when: galaxy_manage_static_setup
  tags: galaxy_immunohub-configuration
  
  # Nikolay 
- name: Include radka_edit_table_tool_data_conf tasks
  include_tasks: radka_edit_table_tool_data_conf.yml
  when: galaxy_manage_static_setup
  tags: galaxy_radka_edit_table_tool_data
  
- name: Include dependency setup tasks
  include_tasks: dependencies.yml
  when: galaxy_fetch_dependencies
  tags:
    - galaxy_fetch_dependencies

- name: Include mutable config setup tasks
  include_tasks: mutable_setup.yml
  when: galaxy_manage_mutable_setup
  tags:
    - galaxy_manage_mutable_setup

- name: Include database management tasks
  include_tasks: database.yml
  when: galaxy_manage_database
  tags:
    - galaxy_manage_database

- name: Include client build tasks
  include_tasks: client.yml
  when: galaxy_build_client
  tags:
    - galaxy_build_client

- name: Include error document setup tasks
  include_tasks: errordocs.yml
  when: galaxy_manage_errordocs
  tags:
    - galaxy_manage_errordocs
