---
# Edit tool data tables

- name: Radka table data config
  block:

     - name: add table child
       xml:
          path: "{{ galaxy_server_dir }}/config/tool_data_table_conf.xml.sample"
          xpath: /tables
          pretty_print: Yes
          add_children:
          - table:
              name: "vdjdb_values"
              comment_char: "#"
              allow_duplicate_entries: "False"

     - name: Add a 'columns, file' element
       xml:
          path: "{{ galaxy_server_dir }}/config/tool_data_table_conf.xml.sample"
          pretty_print: Yes
          xpath: /tables/table
          add_children:
          - columns: "name, value, attribute"
          - file:
                path: "tool-data/vdjdb_values.loc"


  remote_user: "{{ galaxy_remote_users.galaxy | default(omit) }}"
  become: "{{ true if galaxy_become_users.galaxy is defined else __galaxy_become }}"
  become_user: "{{ galaxy_become_users.galaxy | default(ansible_user_id) }}"

