---
# Set start pages

- name: Start setup
  block:

    - name: Copy the Immunohub customized welcome page
      copy: 
        src: "{{ role_path }}/files/welcome.html.immunohub"      
        dest: "{{ galaxy_server_dir }}/static/welcome.html.immunohub"

    - name: Set default welcome page
      command: cp {{ item.src }} {{ item.dest }}
      args:
        creates: "{{ item.dest }}"
      with_items: "{{ galaxy_default_start_welcome }}"


  remote_user: "{{ galaxy_remote_users.galaxy | default(omit) }}"
  become: "{{ true if galaxy_become_users.galaxy is defined else __galaxy_become }}"
  become_user: "{{ galaxy_become_users.galaxy | default(ansible_user_id) }}"
